name = "GenLAProblems"
uuid = "f8228cda-011f-463c-ac28-4f36d81e7604"
authors = ["ea42_github@mail.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
